### ISSUE TITLE
NPE on cyclic object references

### ISSUE THREAD

**Issue by maybeec** [RepreZen/KaiZen-OpenApi-Parser#131]
With the following specification, you will end up in the below stacktrace.
I reduced the file as much as possible, but it seemed to be the cyclic dependency to cause the issue.
Here the spec:

```yaml
openapi: 3.0.0
servers:
  - url: 'https://localhost:8081/devonfw-server/services/rest'
info:
  title: Devon Example
  description: Example of a API definition
  version: 1.0.0
paths:
  /sampledatamanagement/v1/sampledata/custom/{id}:
    get:
      operationId: customMethod
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 100
      responses:
        '200':
          description: Custom Method
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleData'
components:
  schemas:
    SampleData:
      x-component: sampledatamanagement
      type: object
      properties:
        mainData:
          type: object
          description: a single ref to MoreData (one-to-one)
          $ref: '#components/schemas/MoreData'
    MoreData:
      x-component: moredatamanagement
      type: object
      properties:
        master:
          type: object
          description: master data ref (many-to-one)
          $ref: '#components/schemas/SampleData'
```

```
Caused by: java.lang.NullPointerException
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:62)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.<init>(MapOverlay.java:41)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:171)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:142)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
  	at com.reprezen.kaizen.oasparser.ovl3.SchemaImpl.elaborateChildren(SchemaImpl.java:1312)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
  	at com.reprezen.kaizen.oasparser.ovl3.SchemaImpl.<init>(SchemaImpl.java:50)
  	at com.reprezen.kaizen.oasparser.ovl3.SchemaImpl$1._create(SchemaImpl.java:1351)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:26)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:58)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChild(PropertiesOverlay.java:121)
  	at com.reprezen.kaizen.oasparser.ovl3.MediaTypeImpl.elaborateChildren(MediaTypeImpl.java:252)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
  	at com.reprezen.kaizen.oasparser.ovl3.MediaTypeImpl.<init>(MediaTypeImpl.java:31)
  	at com.reprezen.kaizen.oasparser.ovl3.MediaTypeImpl$1._create(MediaTypeImpl.java:280)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:61)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.<init>(MapOverlay.java:41)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:171)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:142)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
  	at com.reprezen.kaizen.oasparser.ovl3.ResponseImpl.elaborateChildren(ResponseImpl.java:282)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
  	at com.reprezen.kaizen.oasparser.ovl3.ResponseImpl.<init>(ResponseImpl.java:32)
  	at com.reprezen.kaizen.oasparser.ovl3.ResponseImpl$1._create(ResponseImpl.java:307)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:61)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.<init>(MapOverlay.java:41)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:171)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:142)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
  	at com.reprezen.kaizen.oasparser.ovl3.OperationImpl.elaborateChildren(OperationImpl.java:718)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
  	at com.reprezen.kaizen.oasparser.ovl3.OperationImpl.<init>(OperationImpl.java:44)
  	at com.reprezen.kaizen.oasparser.ovl3.OperationImpl$1._create(OperationImpl.java:749)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:61)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.<init>(MapOverlay.java:41)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:171)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:142)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
  	at com.reprezen.kaizen.oasparser.ovl3.PathImpl.elaborateChildren(PathImpl.java:434)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
  	at com.reprezen.kaizen.oasparser.ovl3.PathImpl.<init>(PathImpl.java:155)
  	at com.reprezen.kaizen.oasparser.ovl3.PathImpl$1._create(PathImpl.java:460)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:61)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.<init>(MapOverlay.java:41)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:171)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay$MapOverlayFactory._create(MapOverlay.java:142)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
  	at com.reprezen.kaizen.oasparser.ovl3.OpenApi3Impl.elaborateChildren(OpenApi3Impl.java:1103)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
  	at com.reprezen.kaizen.oasparser.ovl3.OpenApi3Impl.<init>(OpenApi3Impl.java:109)
  	at com.reprezen.kaizen.oasparser.ovl3.OpenApi3Impl$1._create(OpenApi3Impl.java:1150)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:40)
  	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:26)
  	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:101)
  	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:90)
  	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:79)
  	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:74)
  	at com.reprezen.kaizen.oasparser.OpenApi3Parser.parse(OpenApi3Parser.java:47)
  	at com.capgemini.cobigen.openapiplugin.inputreader.OpenAPIInputReader.read(OpenAPIInputReader.java:460)
  	at com.capgemini.cobigen.impl.generator.InputInterpreterImpl.read(InputInterpreterImpl.java:57)
  	... 56 more
```

checked version:

```xml
<dependency>
      <groupId>com.reprezen.kaizen</groupId>
      <artifactId>openapi-parser</artifactId>
      <version>0.0.3.201802081723</version>
    </dependency>
```

**Comment by maybeec** [comment]
The reason seems to be here:
https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/master/kaizen-openapi-parser/src/main/java/com/reprezen/kaizen/oasparser/jsonoverlay/ChildOverlay.java#L43

All references are resolved in place during traversal.

**Comment by maybeec** [comment]
We have a serious issue with that in production and I need some help here about the bug analysis. I tried to make the overlay resolution lazy. However, the processing of the overlay is not really clear to me, but maybe I am even hunting the wrong idea as the NPE has even not yet shifted to any other error after adapting the code so far.

Any ideas/hints @andylowry?

**Comment by andylowry** [comment]
@maybeec I'm looking at this now. Hopefully will have something for you later today.

**Comment by maybeec** [comment]
Thanks a lot! Let me know when I can help.

**Comment by andylowry** [comment]
Addressed in #138

**Comment by andylowry** [comment]
This is addressed in #146

**Comment by andylowry** [comment]
@maybeec Please close this issue if it new release works for you. Thx

**Comment by maybeec** [comment]
just wrote a test with the following yaml file (which is not even cyclic):

```yaml
openapi: 3.0.0
servers:
  - url: 'http://any'
info:
  title: any
  description: any
  version: 0.0.0
paths:
  /customMethod:
    get:
      operationId: customMethod
      responses:
        '200':
          description: Custom Method
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleData'
components:
  schemas:
    SampleData:
      x-component: comp
      type: object
      properties:
        mainData:
          type: object
          description: a single ref to MoreData (one-to-one)
          $ref: '#components/schemas/MoreData'
    MoreData:
      x-component: comp
      type: object
      any:
        counter:
          type: integer
          description: any
```

and got

```
java.lang.NullPointerException
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:69)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.elaborate(MapOverlay.java:45)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
	at com.reprezen.kaizen.oasparser.ovl3.SchemaImpl.elaborateChildren(SchemaImpl.java:1303)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.elaborate(PropertiesOverlay.java:188)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:26)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:58)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChild(PropertiesOverlay.java:121)
	at com.reprezen.kaizen.oasparser.ovl3.MediaTypeImpl.elaborateChildren(MediaTypeImpl.java:246)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.elaborate(PropertiesOverlay.java:188)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:68)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.elaborate(MapOverlay.java:45)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
	at com.reprezen.kaizen.oasparser.ovl3.ResponseImpl.elaborateChildren(ResponseImpl.java:276)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.elaborate(PropertiesOverlay.java:188)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:68)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.elaborate(MapOverlay.java:45)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
	at com.reprezen.kaizen.oasparser.ovl3.OperationImpl.elaborateChildren(OperationImpl.java:707)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.elaborate(PropertiesOverlay.java:188)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:68)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.elaborate(MapOverlay.java:45)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
	at com.reprezen.kaizen.oasparser.ovl3.PathImpl.elaborateChildren(PathImpl.java:427)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.elaborate(PropertiesOverlay.java:188)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.fillWithJson(MapOverlay.java:68)
	at com.reprezen.kaizen.oasparser.jsonoverlay.MapOverlay.elaborate(MapOverlay.java:45)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildOverlay.<init>(ChildOverlay.java:65)
	at com.reprezen.kaizen.oasparser.jsonoverlay.ChildMapOverlay.<init>(ChildMapOverlay.java:26)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.createChildMap(PropertiesOverlay.java:137)
	at com.reprezen.kaizen.oasparser.ovl3.OpenApi3Impl.elaborateChildren(OpenApi3Impl.java:1081)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.ensureElaborated(PropertiesOverlay.java:48)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.maybeElaborateChildrenAtCreation(PropertiesOverlay.java:42)
	at com.reprezen.kaizen.oasparser.jsonoverlay.PropertiesOverlay.elaborate(PropertiesOverlay.java:188)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:44)
	at com.reprezen.kaizen.oasparser.jsonoverlay.OverlayFactory.create(OverlayFactory.java:26)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:101)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:90)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:79)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:74)
	at com.reprezen.kaizen.oasparser.OpenApi3Parser.parse(OpenApi3Parser.java:47)
	at com.capgemini.cobigen.openapiplugin.inputreader.OpenAPIInputReader.read(OpenAPIInputReader.java:472)
	at com.capgemini.cobigen.openapiplugin.unittest.inputreader.OpenAPIInputReaderTest.getInputs(OpenAPIInputReaderTest.java:214)
	at com.capgemini.cobigen.openapiplugin.unittest.inputreader.OpenAPIInputReaderTest.testPropertyRefOneToOne(OpenAPIInputReaderTest.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by maybeec** [comment]
I used

```xml
<dependency>
      <groupId>com.reprezen.kaizen</groupId>
      <artifactId>openapi-parser</artifactId>
      <version>0.0.3.201803041924</version>
    </dependency>
```

@andylowry any idea?

**Comment by andylowry** [comment]
Hi Malte. You're missing the initial slash in the fragment on the ref 
I've colored red below.

Clearly the parser shouldn't crash NPE in that case, so I'll create an 
issue for this, but hopefully fixing the schema will get you back in 
operation.

Andy

**Comment by maybeec** [comment]
Oh you are right! Thanks.
Two remarks on that:

1. you should never throw an NPE in case of anything is behaving odd. Currently, there is neither any parse exception thrown at all, nor any validation going on as it seems you are reading openAPI files with a JSON parser. This somehow ma ycause you some more work as users (including me) are not pointed to their own faults in the openAPI file :). How do you provide any parsing error information to the user in your eclipse openAPI editor if this is not given by the parser itself?
2. http://editor.swagger.io/ accepts also references without a leading slash, although I do not know the semantics of it. You may want to check the standard, what it could be. Either swagger or KaiZen seems to be wrong here.

Best Regards,
Malte

**Comment by maybeec** [comment]
Thanks a lot for your efforts to make this work! I will close this issue now as the original issues seem to be fixed.

**Comment by andylowry** [comment]
Hi Malte.

Re Q1:

There is validation built into the parser, but it requires careful review and tests, and it hasn't been updated to reflect the handful of changes introduced since RC0. The OpenApi3 object has methods isValid() and getValidationItems() that show you what the parser noted. You're right that the parser should not throw NPE.

You asked:
>    How do you provide any parsing error information to the user in your eclipse openAPI editor if this is not given by the parser itself?

The editor performs validation using a (not yet official) JSON Schema. It does not make use of this parser and was created by extending a pre-existing YAML public-domain editor (YEdit). It also has some flaws, e.g. I noticed it doesn't seem to understand the extensions in your file, but its flaws will not generally line up with the parser's flaws.

2. The [JSONRef ](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03)spec references the [JSONPointer](https://tools.ietf.org/html/draft-ietf-appsawg-json-pointer-04) spec:

>    If a URI contains a fragment identifier, then the fragment should be
   resolved per the fragment resolution mechansim of the referrant
   document.  If the representation of the referrant document is JSON,
   then the fragment identifier SHOULD be interpreted as a
   [JSON-Pointer] 

The JSONPointer spec says:

> A JSON Pointer is a [Unicode] string containing a sequence of zero or
   more reference tokens, each prefixed by a '/' (%x2F) character.

The "reference tokens" are the property names and array indexes in the pointer. Each - including the first - must be preceded by a slash. The only valid JSONPointer that does not start with a slash is the empty one, which refers to the entire enclosing JSON document.

So I would definitely say this is a bug in editor.swagger.io. We had many issues with our Swagger support because people treated either that or Swagger-UI or the Java Swagger parser as definitive, but the fact is that they all had almost completely separate implementations and almost completely separate bugs - and many of them! I believe the situation is improving with OAS3, but it's still far from uniform, and there really isn't any tool (obviously, including the KaiZen parser) that can definitively tell you that your model does or does not comply with the spec. Even if there were an officially endorsed JSON Schema definition for OAS3 (there is for OAS2), there are many requirements in the spec that cannot be expressed in JSON Schema, so that would also not be definitive.

It's sort of a sucky place we're in. I had hoped that the KaiZen parser would be a contender for most accurate parser, but my availability has not been sufficient to make the needed progress in that area. Some day...

**Comment by maybeec** [comment]
Really appriciate your extensive feedback and insights!
@jdiazgon, you should definitively read it :)

> So I would definitely say this is a bug in editor.swagger.io. We had many issues with our Swagger support because people treated either that or Swagger-UI or the Java Swagger parser as definitive

I observed the same issue, that guys modeling their openAPI files with swagger editors and complain about them, if their spec later on don't work in a different toolset. But ask the JDT guys, who are fighting as well with the spec of Java. I think it is good to have multiple implementations and I really see this as an opportunity.

>  but my availability has not been sufficient to make the needed progress in that area. Some day...

As we also use it, we will keep track of issues, we observe and from time to time also provide some PRs as well. Hope we can help to some extend in our time constraints as well!

**Comment by andylowry** [comment]
Thanks @maybeec. You're probably right about the benefit of multiple independent implementations, but I confess that sometimes it's hard to see it as anything other than a curse :-)

I appreciate your participation, and I'll look into the Travis config you pointed me at shortly. I had no idea there was such a thing available! We use TeamCity in general for our software, and that's where I'm building things now. But it's a private build service, not suitable for use by other contributors.

**Comment by maybeec** [comment]
With travis, you get everything for free in open source projects :)
You even get feedback directly on PRs about the test executions and so on. So it will even give you some quality gate before merging.
You potentially have to activate travis ci over your repository settings to make it work after merging the PR, but this is just about 10s and you are done ;)
