### ISSUE TITLE
Fail to validate links

### ISSUE THREAD

**Issue by ghillairet** [RepreZen/KaiZen-OpenApi-Parser#51]
LinkValidator validation fails on operationRefs.

Test file:

```yaml
openapi: "3.0.0"
info:
  title: Headers Object
  version: "1.0.0"
servers:
  - url: https://api.uber.com/v1   
paths: 
  /pets:
    get:
      summary: Read
      description: Provide details for the entire list (for collection resources) or an item (for object resources)
      responses:
        '200':
          description: A simple string response
          content:
            text/plain:
              schema:
                type: string
components:             
  links:
    UserRepositories:
      operationRef: "#/paths/~1pets/get/"
```

Stacktrace

```
java.lang.NullPointerException
	at com.reprezen.kaizen.oasparser.val3.LinkValidator.checkParameters(LinkValidator.java:80)
	at com.reprezen.kaizen.oasparser.val3.LinkValidator.validateObject(LinkValidator.java:42)
	at com.reprezen.kaizen.oasparser.val3.LinkValidator.validateObject(LinkValidator.java:32)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.validate(ObjectValidatorBase.java:23)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase$1.run(ValidatorBase.java:51)
	at com.reprezen.kaizen.oasparser.val.ValidationResults.withCrumb(ValidationResults.java:116)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:48)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase$3.run(ValidatorBase.java:186)
	at com.reprezen.kaizen.oasparser.val.ValidationResults.withCrumb(ValidationResults.java:116)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validateMap(ValidatorBase.java:179)
	at com.reprezen.kaizen.oasparser.val3.OpenApi3Validator$1.run(OpenApi3Validator.java:89)
	at com.reprezen.kaizen.oasparser.val.ValidationResults.withCrumb(ValidationResults.java:116)
	at com.reprezen.kaizen.oasparser.val3.OpenApi3Validator.validateObject(OpenApi3Validator.java:70)
	at com.reprezen.kaizen.oasparser.val3.OpenApi3Validator.validateObject(OpenApi3Validator.java:37)
	at com.reprezen.kaizen.oasparser.val.ObjectValidatorBase.validate(ObjectValidatorBase.java:23)
	at com.reprezen.kaizen.oasparser.val.ValidatorBase.validate(ValidatorBase.java:42)
	at com.reprezen.kaizen.oasparser.ovl3.OpenApi3Impl.validate(OpenApi3Impl.java:59)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:92)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:50)
```

**Comment by tfesenko** [comment]
https://github.com/ModelSolv/RepreZen/pull/1328#issuecomment-317503851 is probably caused by this issue

**Comment by andylowry** [comment]
Partially addressed in #74
