### ISSUE TITLE
QuickStart will not run

### ISSUE THREAD

**Issue by nqzero** [RepreZen/KaiZen-OpenApi-Parser#65]
using the code at:
https://github.com/RepreZen/KaiZen-OpenApi-Parser/blob/master/GettingStarted.md

(renamed to Demo but otherwise unchanged) i get

```
java -cp target/classes:libs/\* Demo -n
Exception in thread "main" java.lang.NullPointerException
	at com.reprezen.kaizen.oasparser.OpenApiParser.isVersion3(OpenApiParser.java:115)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:96)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:88)
	at com.reprezen.kaizen.oasparser.OpenApiParser.parse(OpenApiParser.java:77)
	at Demo.processModel(Demo.java:26)
	at Demo.main(Demo.java:21)
```

i've tried clean builds with the last 10 commits

**Comment by andylowry** [comment]
Fixed in #68

**Comment by tfesenko** [comment]
Hi @nqzero! 
Thank you for reporting this issue. We updated the code snippet, please try the new instructions and let us know how it works for you.

**Comment by andylowry** [comment]
@nqzero Closing this issue... please reopen if you still see problems. Thanks!
